BurgerTemplateMethod/Models/Burger.cs
using System.ComponentModel.DataAnnotations;

namespace BurgerTemplateMethod.Models
{
    public  class Burger
    {
        public int Id { get; set; }
        [Required]
        public string? Name { get; set; }
        public bool WithCheese { get; set; }
        [Range(0.01, 9999.99)]
        public decimal Precio { get; set; }

        public string? Descripcion { get; set; }
    }

}

BurgerTemplateMethod/Controllers/AmericanasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BurgerTemplateMethod.Data;
using BurgerTemplateMethod.Models;

namespace BurgerTemplateMethod.Controllers
{
    public class AmericanasController : Controller
    {
        private readonly BurgerTemplateMethodContext _context;

        public AmericanasController(BurgerTemplateMethodContext context)
        {
            _context = context;
        }

        // GET: Americanas
        public async Task<IActionResult> Index()
        {
              return View(await _context.Americana.ToListAsync());
        }

        // GET: Americanas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Americana == null)
            {
                return NotFound();
            }

            var americana = await _context.Americana
                .FirstOrDefaultAsync(m => m.Id == id);
            if (americana == null)
            {
                return NotFound();
            }

            return View(americana);
        }

        // GET: Americanas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Americanas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,WithCheese,Precio, Descripcion")] Americana americana)
        {
            americana.Name = "Americana";
            americana.WithCheese = true;
            americana.Precio = 9;
            americana.Descripcion = "Hamburguesa con tocino, doble carne, queso cheddar, cebolla crispy, lechuga y cebolla";

            if (ModelState.IsValid)
            {
                _context.Add(americana);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(americana);
        }

        // GET: Americanas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Americana == null)
            {
                return NotFound();
            }

            var americana = await _context.Americana.FindAsync(id);
            if (americana == null)
            {
                return NotFound();
            }
            return View(americana);
        }

        // POST: Americanas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,WithCheese,Precio")] Americana americana)
        {
            if (id != americana.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(americana);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AmericanaExists(americana.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(americana);
        }

        // GET: Americanas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Americana == null)
            {
                return NotFound();
            }

            var americana = await _context.Americana
                .FirstOrDefaultAsync(m => m.Id == id);
            if (americana == null)
            {
                return NotFound();
            }

            return View(americana);
        }

        // POST: Americanas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Americana == null)
            {
                return Problem("Entity set 'BurgerTemplateMethodContext.Americana'  is null.");
            }
            var americana = await _context.Americana.FindAsync(id);
            if (americana != null)
            {
                _context.Americana.Remove(americana);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AmericanaExists(int id)
        {
          return _context.Americana.Any(e => e.Id == id);
        }
    }
}

BurgerTemplateMethod/Controllers/HawaianasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BurgerTemplateMethod.Data;
using BurgerTemplateMethod.Models;

namespace BurgerTemplateMethod.Controllers
{
    public class HawaianasController : Controller
    {
        private readonly BurgerTemplateMethodContext _context;

        public HawaianasController(BurgerTemplateMethodContext context)
        {
            _context = context;
        }

        // GET: Hawaianas
        public async Task<IActionResult> Index()
        {
              return View(await _context.Hawaiana.ToListAsync());
        }

        // GET: Hawaianas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Hawaiana == null)
            {
                return NotFound();
            }

            var hawaiana = await _context.Hawaiana
                .FirstOrDefaultAsync(m => m.Id == id);
            if (hawaiana == null)
            {
                return NotFound();
            }

            return View(hawaiana);
        }

        // GET: Hawaianas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Hawaianas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( Hawaiana hawaiana)
        {
            hawaiana.Name = "Hawaiana";
            hawaiana.WithCheese = false;
            hawaiana.Precio = 7;
            hawaiana.Descripcion = "Hamburguesa de una carne, con pina, y mermelada";
            if (ModelState.IsValid)
            {
                _context.Add(hawaiana);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(hawaiana);
        }

        // GET: Hawaianas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Hawaiana == null)
            {
                return NotFound();
            }

            var hawaiana = await _context.Hawaiana.FindAsync(id);
            if (hawaiana == null)
            {
                return NotFound();
            }
            return View(hawaiana);
        }

        // POST: Hawaianas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,WithCheese,Precio,Descripcion")] Hawaiana hawaiana)
        {
            if (id != hawaiana.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(hawaiana);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HawaianaExists(hawaiana.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(hawaiana);
        }

        // GET: Hawaianas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Hawaiana == null)
            {
                return NotFound();
            }

            var hawaiana = await _context.Hawaiana
                .FirstOrDefaultAsync(m => m.Id == id);
            if (hawaiana == null)
            {
                return NotFound();
            }

            return View(hawaiana);
        }

        // POST: Hawaianas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Hawaiana == null)
            {
                return Problem("Entity set 'BurgerTemplateMethodContext.Hawaiana'  is null.");
            }
            var hawaiana = await _context.Hawaiana.FindAsync(id);
            if (hawaiana != null)
            {
                _context.Hawaiana.Remove(hawaiana);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HawaianaExists(int id)
        {
          return _context.Hawaiana.Any(e => e.Id == id);
        }
    }
}

BurgerTemplateMethod/Controllers/RancherasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BurgerTemplateMethod.Data;
using BurgerTemplateMethod.Models;

namespace BurgerTemplateMethod.Controllers
{
    public class RancherasController : Controller
    {
        private readonly BurgerTemplateMethodContext _context;

        public RancherasController(BurgerTemplateMethodContext context)
        {
            _context = context;
        }

        // GET: Rancheras
        public async Task<IActionResult> Index()
        {
              return View(await _context.Ranchera.ToListAsync());
        }

        // GET: Rancheras/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Ranchera == null)
            {
                return NotFound();
            }

            var ranchera = await _context.Ranchera
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ranchera == null)
            {
                return NotFound();
            }

            return View(ranchera);
        }

        // GET: Rancheras/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Rancheras/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Ranchera ranchera)
        {
            ranchera.Name = "Hawaiana";
            ranchera.WithCheese = true;
            ranchera.Precio = 10;
            ranchera.Descripcion = "Hamburguesa de dos carnes, con huevo, queso, salchicha, tocino, vegetales";
            if (ModelState.IsValid)
            {
                _context.Add(ranchera);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(ranchera);
        }

        // GET: Rancheras/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Ranchera == null)
            {
                return NotFound();
            }

            var ranchera = await _context.Ranchera.FindAsync(id);
            if (ranchera == null)
            {
                return NotFound();
            }
            return View(ranchera);
        }

        // POST: Rancheras/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,WithCheese,Precio,Descripcion")] Ranchera ranchera)
        {
            if (id != ranchera.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ranchera);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RancheraExists(ranchera.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ranchera);
        }

        // GET: Rancheras/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Ranchera == null)
            {
                return NotFound();
            }

            var ranchera = await _context.Ranchera
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ranchera == null)
            {
                return NotFound();
            }

            return View(ranchera);
        }

        // POST: Rancheras/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Ranchera == null)
            {
                return Problem("Entity set 'BurgerTemplateMethodContext.Ranchera'  is null.");
            }
            var ranchera = await _context.Ranchera.FindAsync(id);
            if (ranchera != null)
            {
                _context.Ranchera.Remove(ranchera);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RancheraExists(int id)
        {
          return _context.Ranchera.Any(e => e.Id == id);
        }
    }
}

BurgerTemplateMethod/Views/Burgers/Create.cshtml
@model BurgerTemplateMethod.Models.Burger

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Burger</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="WithCheese" /> @Html.DisplayNameFor(model => model.WithCheese)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
            <div class="form-group">
                <a asp-action="Create" asp-controller="Americanas" class="btn btn-primsary" >Insertar Americana</a>
            </div>
            <div class="form-group">
                <a asp-action="Create" asp-controller="Hawaianas" class="btn btn-primary">Insertar Hawaiana</a>
            </div>
            <div class="form-group">
                <a asp-action="Create" asp-controller="Rancheras" class="btn btn-primary">Insertar Ranchera</a>
            </div>
           
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BurgerTemplateMethod/Views/Burgers/Delete.cshtml
@model BurgerTemplateMethod.Models.Burger

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Burger</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WithCheese)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WithCheese)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BurgerTemplateMethod/Views/Burgers/Details.cshtml
@model BurgerTemplateMethod.Models.Burger

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Burger</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WithCheese)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WithCheese)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

BurgerTemplateMethod/Views/Burgers/Edit.cshtml
@model BurgerTemplateMethod.Models.Burger

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Burger</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="WithCheese" /> @Html.DisplayNameFor(model => model.WithCheese)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BurgerTemplateMethod/Views/Burgers/Index.cshtml
@model IEnumerable<BurgerTemplateMethod.Models.Burger>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WithCheese)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Precio)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WithCheese)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>